version: 2.1
jobs:
  validate_package_appinspect:
    docker:
      # specify the version you desire here
      - image: circleci/python:3

    working_directory: ~/

    steps:
      - run:
          name: mkdir
          command: |
            mkdir ~/circleci_app
            mkdir ~/package
      - checkout:
          path: ~/circleci_app/

      - run:
          name: remove unpackaged files
          command: |
            rm -r -f ~/circleci_app/.circleci
            rm -r -f ~/circleci_app/.git
            rm -r -f ~/circleci_app/img
            rm -r -f ~/circleci_app/local
            rm -f ~/circleci_app/.gitignore
      - run:
          name: setup virtualenv
          command: |
            pip3 install virtualenv
            mkdir ~/virtualenv
            cd ~/virtualenv
            virtualenv slim
            cd slim
            source bin/activate
            pip3 install semantic_version
            wget https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz \
              -O splunk-packaging-toolkit.tar.gz
            # Permission error without sudo
            sudo pip3 install splunk-packaging-toolkit.tar.gz
            PYTHON_HOME=~/virtualenv/slim
            PATH="${PYTHON_HOME}/bin:$PATH"
      - run:
          name: validate app
          command: |
            slim validate ~/circleci_app/alert_microsoftteams
      - run:
          name: package app
          command: |
            slim package -o ~/package/ ~/circleci_app/alert_microsoftteams
            echo "export PACKAGE_FILE=`ls ~/package/circleci_app-*.tar.gz`" >> $BASH_ENV
      - store_artifacts:
          path: ~/package

      - run:
          name: get appinspect token
          command: |
            echo "export APPINSPECT_TOKEN=`curl -X GET \
            -u $SPLUNKCOM_USER:$SPLUNKCOM_PASSWORD \
            --url "https://api.splunk.com/2.0/rest/login/splunk" | jq \".data.token\"`" >> $BASH_ENV
      - run:
          name: submit an app validation
          command: |
            curl -X POST \
            -H "Authorization: bearer $APPINSPECT_TOKEN" \
            -H "Cache-Control: no-cache" \
            -F "app_package=@\"$PACKAGE_FILE\"" \
            --url "https://appinspect.splunk.com/v1/app/validate" > ~/circleci_appinspect.json
      - store_artifacts:
          path: ~/circleci_appinspect.json

      - run:
          name: submit an app cloud validation
          command: |
            curl -X POST \
            -H "Authorization: bearer $APPINSPECT_TOKEN" \
            -H "Cache-Control: no-cache" \
            -F "app_package=@\"$PACKAGE_FILE\"" \
            -F "included_tags=cloud" \
            --url "https://appinspect.splunk.com/v1/app/validate" > ~/circleci_appinspect_cloud.json
      - store_artifacts:
          path: ~/circleci_appinspect_cloud.json

orbs:


workflows:
  main:
    jobs:
      - validate_package_appinspect