name: Test and Build

on:
  pull_request:
    branches:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

  appinspect:
    runs-on: ubuntu-latest
    container: ghcr.io/ermontross/appinspect:latest

    steps:
      - uses: actions/checkout@v2

      - name: Run AppInspect
        run: splunk-appinspect inspect alert_microsoftteams --output-file appinspect_result.json --mode precert

      - name: Upload AppInspect Results
        uses: actions/upload-artifact@v2
        with:
          name: appinspect
          path: appinspect_result.json